// Package sellers provides primitives to interact the openapi HTTP API.
//
// Code generated by go-sdk-codegen DO NOT EDIT.
package sellers

// Error defines model for Error.
type Error struct {

	// An error code that identifies the type of error that occured.
	Code string `json:"code"`

	// Additional details that can help the caller understand or fix the issue.
	Details *string `json:"details,omitempty"`

	// A message that describes the error condition in a human-readable form.
	Message string `json:"message"`
}

// ErrorList defines model for ErrorList.
type ErrorList []Error

// GetMarketplaceParticipationsResponse defines model for GetMarketplaceParticipationsResponse.
type GetMarketplaceParticipationsResponse struct {

	// A list of error responses returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`

	// List of marketplace participations.
	Payload *MarketplaceParticipationList `json:"payload,omitempty"`
}

// Marketplace defines model for Marketplace.
type Marketplace struct {

	// The ISO 3166-1 alpha-2 format country code of the marketplace.
	CountryCode string `json:"countryCode"`

	// The ISO 4217 format currency code of the marketplace.
	DefaultCurrencyCode string `json:"defaultCurrencyCode"`

	// The ISO 639-1 format language code of the marketplace.
	DefaultLanguageCode string `json:"defaultLanguageCode"`

	// The domain name of the marketplace.
	DomainName string `json:"domainName"`

	// The encrypted marketplace value.
	Id string `json:"id"`

	// Marketplace name.
	Name string `json:"name"`
}

// MarketplaceParticipation defines model for MarketplaceParticipation.
type MarketplaceParticipation struct {

	// Detailed information about an Amazon market where a seller can list items for sale and customers can view and purchase items.
	Marketplace Marketplace `json:"marketplace"`

	// Detailed information that is specific to a seller in a Marketplace.
	Participation Participation `json:"participation"`
}

// MarketplaceParticipationList defines model for MarketplaceParticipationList.
type MarketplaceParticipationList []MarketplaceParticipation

// Participation defines model for Participation.
type Participation struct {

	// Specifies if the seller has suspended listings. True if the seller Listing Status is set to Inactive, otherwise False.
	HasSuspendedListings bool `json:"hasSuspendedListings"`
	IsParticipating      bool `json:"isParticipating"`
}
